import json

from techno_search.validation import (
    validate_candidate_mapping,
    validate_report_directory,
    validate_report_manifest,
)


def test_validate_candidate_rejects_bad_track() -> None:
    result = validate_candidate_mapping(
        {
            "candidate_id": "bad-track",
            "track": "optical",
            "features": {},
        }
    )

    assert result.ok is False
    assert "Unsupported candidate track" in result.errors[0]


def test_validate_candidate_rejects_non_mapping_features() -> None:
    result = validate_candidate_mapping(
        {
            "candidate_id": "bad-features",
            "track": "radio",
            "features": ["not", "a", "mapping"],
        }
    )

    assert result.ok is False
    assert "candidate.features must be a mapping" in result.errors


def test_validate_report_directory_rejects_missing_candidate_manifest(tmp_path) -> None:
    packet = {
        "candidate_id": "report-without-manifest",
        "track": "radio",
        "source_ids": [],
        "features": {},
        "posterior": {
            "technosignature_interest": 0.1,
            "natural_source": 0.1,
            "human_interference": 0.1,
            "instrumental_artifact": 0.1,
            "catalog_or_processing_error": 0.1,
            "known_object": 0.1,
            "noise_or_low_confidence": 0.4,
        },
        "scores": {
            "false_positive_probability": 0.9,
            "signal_reality_confidence": 0.1,
            "novelty_score": 0.1,
            "followup_value": 0.1,
            "review_readiness": 0.1,
        },
        "recommended_pathway": "do_not_submit_false_positive",
        "positive_evidence": [],
        "negative_evidence": [],
        "blocking_issues": [],
        "provenance": {},
        "schema_version": "techno_search_packet_v1",
        "config_version": "scoring_v0",
        "disclaimer": (
            "This is an unconfirmed candidate/anomaly generated by a publication-grade "
            "technosignature search pipeline. It is not evidence of a confirmed "
            "technosignature. Further review and independent validation are required."
        ),
        "false_positive_discussion": "False positives remain the default hypothesis.",
    }
    (tmp_path / "candidate.json").write_text(json.dumps(packet), encoding="utf-8")

    result = validate_report_directory(tmp_path)

    assert result.ok is False
    assert "missing manifest" in result.errors[0]


def test_validate_report_directory_rejects_empty_directory(tmp_path) -> None:
    result = validate_report_directory(tmp_path)

    assert result.ok is False
    assert result.errors == ("report directory contains no candidate JSON packets",)


def test_validate_report_manifest_accepts_missing_optional_plot_artifacts() -> None:
    result = validate_report_manifest(
        {
            "candidate_id": "optional-plots",
            "track": "radio",
            "recommended_pathway": "candidate_review_packet",
            "schema_version": "techno_search_packet_v1",
            "markdown_path": "optional-plots.md",
            "json_path": "optional-plots.json",
            "config_version": "scoring_v0",
            "code_commit": None,
            "generated_at_utc": "2026-05-02T00:00:00+00:00",
            "provenance_summary": {},
        }
    )

    assert result.ok is True
