#!/usr/bin/env bash
# create_data_inventory.sh — Find all H5/dat data files near the repo and write
# docs/LOCAL_DATA_INVENTORY.md so future agents never need to ask the user.
#
# Usage (run from repo root):
#   bash scripts/create_data_inventory.sh
#
# What it does:
#   1. Searches . (repo root) for *.h5 and *.dat files (skips .git)
#   2. Also searches ../  one level up (sibling data directories)
#   3. Writes docs/LOCAL_DATA_INVENTORY.md with all findings
#   4. Prints the path to the inventory file
#
# Does NOT modify, move, or delete any files.
# Safe to re-run — overwrites the inventory with fresh results.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INVENTORY="$REPO_ROOT/docs/LOCAL_DATA_INVENTORY.md"
NOW="$(date '+%Y-%m-%d %H:%M:%S %Z')"
MACHINE="$(hostname)"

log() { echo "[$(date '+%H:%M:%S')] $*"; }

log "=== create_data_inventory.sh ==="
log "Repo root : $REPO_ROOT"
log "Inventory : $INVENTORY"
log ""

# ---------------------------------------------------------------------------
# Find H5 files (repo root + one level up, skipping .git and .venv)
# ---------------------------------------------------------------------------
log "Searching for *.h5 files from repo root (takes ~5s) ..."
H5_IN_REPO=$(find "$REPO_ROOT" \
    -name "*.h5" \
    -not -path "*/.git/*" \
    -not -path "*/.venv/*" \
    -not -path "*/node_modules/*" \
    2>/dev/null | sort)

H5_SIBLING=$(find "$(dirname "$REPO_ROOT")" -maxdepth 3 \
    -name "*.h5" \
    -not -path "*/.git/*" \
    -not -path "*/.venv/*" \
    2>/dev/null | sort)

log "Searching for *.dat files from repo root ..."
DAT_IN_REPO=$(find "$REPO_ROOT" \
    -name "*.dat" \
    -not -path "*/.git/*" \
    -not -path "*/.venv/*" \
    2>/dev/null | sort)

# ---------------------------------------------------------------------------
# Count results
# ---------------------------------------------------------------------------
H5_REPO_COUNT=$(echo "$H5_IN_REPO" | grep -c . 2>/dev/null || echo 0)
H5_SIB_COUNT=$(echo "$H5_SIBLING"  | grep -c . 2>/dev/null || echo 0)
DAT_COUNT=$(echo "$DAT_IN_REPO"    | grep -c . 2>/dev/null || echo 0)

log "Found $H5_REPO_COUNT H5 file(s) in repo tree"
log "Found $H5_SIB_COUNT H5 file(s) in sibling directories"
log "Found $DAT_COUNT .dat file(s) in repo tree"

# ---------------------------------------------------------------------------
# Write inventory
# ---------------------------------------------------------------------------
cat > "$INVENTORY" <<EOF
# LOCAL DATA INVENTORY

**Generated:** $NOW
**Machine:** $MACHINE
**Repo root:** $REPO_ROOT

This file is auto-generated by \`scripts/create_data_inventory.sh\`.
Re-run that script whenever data files are added or moved.
Agents: read this file instead of asking the user where data files are.

---

## H5 Files (Raw GBT/turboSETI Input)

H5 files are large raw GBT observation files. They are gitignored and not
committed to the repo. turboSETI reads these and produces \`.dat\` hit tables.

### In Repo Tree

\`\`\`
EOF

if [[ -z "$H5_IN_REPO" ]]; then
    echo "(none found)" >> "$INVENTORY"
else
    echo "$H5_IN_REPO" >> "$INVENTORY"
fi

cat >> "$INVENTORY" <<'EOF'
```

### In Sibling Directories (one level up from repo root)

```
EOF

if [[ -z "$H5_SIBLING" ]]; then
    echo "(none found)" >> "$INVENTORY"
else
    echo "$H5_SIBLING" >> "$INVENTORY"
fi

cat >> "$INVENTORY" <<'EOF'
```

---

## turboSETI Hit Tables (.dat files)

`.dat` files are turboSETI output — small text files with detected hit rows.
These are the primary pipeline inputs and are stored in `data/`.

```
EOF

if [[ -z "$DAT_IN_REPO" ]]; then
    echo "(none found — run scripts/download_calibration_corpus.sh)" >> "$INVENTORY"
else
    echo "$DAT_IN_REPO" >> "$INVENTORY"
fi

cat >> "$INVENTORY" <<'EOF'
```

---

## Standard Data Directory Layout

| Directory | Contents |
|---|---|
| `data/bl_hits/` | Voyager 1 hit table from `download_bl_hits.sh` |
| `data/calibration_corpus/` | BL calibration .dat files + provenance sidecars |

---

## Scientific Guardrail

H5 files and .dat files are calibration inputs only. They do not constitute
detection claims. No result authorizes external submission. Provenance sidecars
(`.dat.provenance.json`) must be approved before pipeline ingestion.
EOF

log ""
log "=== Inventory written to: $INVENTORY ==="
log ""
log "Next steps:"
log "  1. git add docs/LOCAL_DATA_INVENTORY.md"
log "  2. git commit -m 'Add local data inventory (closes repeated H5 location question)'"
log "  3. git push -u origin claude/general-session-Bb2dZ"
log ""

# Print summary to screen
echo ""
echo "========================================"
echo " DATA INVENTORY SUMMARY"
echo "  H5 in repo tree    : $H5_REPO_COUNT"
echo "  H5 in siblings     : $H5_SIB_COUNT"
echo "  .dat in repo tree  : $DAT_COUNT"
echo "  Inventory written  : $INVENTORY"
echo "========================================"

if [[ "$H5_REPO_COUNT" -eq 0 && "$H5_SIB_COUNT" -eq 0 ]]; then
    echo ""
    echo "[WARN] No H5 files found. If you have downloaded them elsewhere,"
    echo "       run: find /path/to/data -name '*.h5' and add to inventory manually."
fi
