#!/usr/bin/env bash
# create_data_inventory.sh — Find H5/dat data files near the repo and write
# docs/LOCAL_DATA_INVENTORY.md so future agents never need to ask the user.
#
# Usage (run from repo root):
#   bash scripts/create_data_inventory.sh
#
# Safe to re-run — overwrites inventory with fresh results.

set -uo pipefail   # Note: NOT -e so grep no-match (exit 1) doesn't kill us

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INVENTORY="$REPO_ROOT/docs/LOCAL_DATA_INVENTORY.md"
NOW="$(date '+%Y-%m-%d %H:%M:%S %Z')"
MACHINE="$(hostname)"

log() { echo "[$(date '+%H:%M:%S')] $*"; }

log "=== create_data_inventory.sh ==="
log "Repo root : $REPO_ROOT"
log "Inventory : $INVENTORY"
log ""

# ---------------------------------------------------------------------------
# Find H5 files (repo root only — scoped, fast ~5s)
# ---------------------------------------------------------------------------
log "Searching for *.h5 files from repo root ..."
mapfile -t H5_FILES < <(find "$REPO_ROOT" \
    -name "*.h5" \
    -not -path "*/.git/*" \
    -not -path "*/.venv/*" \
    -not -path "*/node_modules/*" \
    2>/dev/null | sort)
H5_COUNT="${#H5_FILES[@]}"
log "Found $H5_COUNT H5 file(s)"

log "Searching for *.dat files from repo root ..."
mapfile -t DAT_FILES < <(find "$REPO_ROOT" \
    -name "*.dat" \
    -not -path "*/.git/*" \
    -not -path "*/.venv/*" \
    2>/dev/null | sort)
DAT_COUNT="${#DAT_FILES[@]}"
log "Found $DAT_COUNT .dat file(s)"

# ---------------------------------------------------------------------------
# Write inventory
# ---------------------------------------------------------------------------
{
cat <<HEADER
# LOCAL DATA INVENTORY

**Generated:** $NOW
**Machine:** $MACHINE
**Repo root:** $REPO_ROOT

This file is auto-generated by \`scripts/create_data_inventory.sh\`.
Re-run that script whenever data files are added or moved.
**Agents: read this file instead of asking the user where data files are.**

---

## H5 Files (Raw GBT/turboSETI Input)

H5 files are large raw GBT observation files. They are gitignored and not
committed to the repo. turboSETI reads these and produces \`.dat\` hit tables.

HEADER

echo "Found: $H5_COUNT file(s)"
echo ""
echo '```'
if [[ "$H5_COUNT" -eq 0 ]]; then
    echo "(none found in repo tree)"
else
    for f in "${H5_FILES[@]}"; do
        echo "$f"
    done
fi
echo '```'

cat <<SECTION2

---

## turboSETI Hit Tables (.dat files)

\`.dat\` files are turboSETI output — small text files with detected hit rows.
These are the primary pipeline inputs and are stored in \`data/\`.

SECTION2

echo "Found: $DAT_COUNT file(s)"
echo ""
echo '```'
if [[ "$DAT_COUNT" -eq 0 ]]; then
    echo "(none found — run scripts/download_calibration_corpus.sh)"
else
    for f in "${DAT_FILES[@]}"; do
        echo "$f"
    done
fi
echo '```'

cat <<FOOTER

---

## Standard Data Directory Layout

| Directory | Contents |
|---|---|
| \`data/bl_hits/\` | Voyager 1 hit table from \`download_bl_hits.sh\` |
| \`data/calibration_corpus/\` | BL calibration .dat files + provenance sidecars |

---

## Scientific Guardrail

H5 files and .dat files are calibration inputs only. They do not constitute
detection claims. No result authorizes external submission. Provenance sidecars
(\`.dat.provenance.json\`) must be approved before pipeline ingestion.
FOOTER
} > "$INVENTORY"

log ""
log "=== Inventory written to: $INVENTORY ==="
log ""

echo ""
echo "========================================"
echo " DATA INVENTORY SUMMARY"
echo "  H5 files  : $H5_COUNT"
echo "  .dat files: $DAT_COUNT"
echo "  Written to: docs/LOCAL_DATA_INVENTORY.md"
echo "========================================"
echo ""
echo "Next:"
echo "  git add docs/LOCAL_DATA_INVENTORY.md"
echo "  git commit -m 'Add local data inventory'"
echo "  git push origin main"
