"""Candidate report generation."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from techno_search.constants import DEFAULT_SCHEMA_VERSION, DEFAULT_SCORING_CONFIG_VERSION
from techno_search.plotting import (
    PLOT_ARTIFACT_DISCLAIMER,
    PlotArtifact,
    write_synthetic_plot_artifacts,
)
from techno_search.provenance import candidate_provenance_record, git_commit
from techno_search.schemas import Pathway, ScoredCandidate

REQUIRED_DISCLAIMER = (
    "This is an unconfirmed candidate/anomaly generated by a publication-grade "
    "technosignature search pipeline. It is not evidence of a confirmed "
    "technosignature. Further review and independent validation are required."
)


@dataclass(frozen=True)
class ReportPaths:
    """Paths written for a candidate review packet."""

    markdown_path: Path
    json_path: Path
    manifest_path: Path
    plot_artifact_paths: tuple[Path, ...] = ()


def candidate_packet(scored: ScoredCandidate) -> dict[str, Any]:
    """Return the canonical JSON-serializable candidate packet."""

    packet = scored.as_dict()
    packet["schema_version"] = DEFAULT_SCHEMA_VERSION
    packet["config_version"] = _config_version(scored)
    packet["disclaimer"] = REQUIRED_DISCLAIMER
    packet["operator_review"] = _operator_review(scored)
    packet["false_positive_discussion"] = _false_positive_discussion(scored)
    return packet


def candidate_packet_json(scored: ScoredCandidate, *, indent: int = 2) -> str:
    """Serialize the canonical candidate packet as deterministic JSON."""

    return json.dumps(candidate_packet(scored), indent=indent, sort_keys=True)


def write_candidate_reports(
    scored: ScoredCandidate,
    output_dir: Path | str,
    *,
    filename_prefix: str | None = None,
    include_plot_artifacts: bool = True,
) -> ReportPaths:
    """Write Markdown and JSON review packets to ``output_dir``.

    Filenames are sanitized from the candidate ID or explicit prefix so candidate
    metadata cannot create nested paths or overwrite arbitrary files.
    """

    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)

    stem = _safe_filename(filename_prefix or scored.candidate.candidate_id)
    markdown_path = destination / f"{stem}.md"
    json_path = destination / f"{stem}.json"
    manifest_path = destination / f"{stem}.manifest.json"
    plot_artifacts = (
        write_synthetic_plot_artifacts(scored, destination, filename_prefix=stem)
        if include_plot_artifacts
        else ()
    )

    markdown_path.write_text(
        candidate_markdown_report(scored, plot_artifacts=plot_artifacts),
        encoding="utf-8",
    )
    json_path.write_text(candidate_packet_json(scored) + "\n", encoding="utf-8")
    manifest_path.write_text(
        report_manifest_json(
            scored,
            markdown_path=markdown_path,
            json_path=json_path,
            plot_artifacts=plot_artifacts,
        )
        + "\n",
        encoding="utf-8",
    )

    return ReportPaths(
        markdown_path=markdown_path,
        json_path=json_path,
        manifest_path=manifest_path,
        plot_artifact_paths=tuple(artifact.path for artifact in plot_artifacts),
    )


def report_manifest(
    scored: ScoredCandidate,
    *,
    markdown_path: Path,
    json_path: Path,
    plot_artifacts: tuple[PlotArtifact, ...] = (),
) -> dict[str, Any]:
    """Return a persistence manifest for written candidate reports."""

    return {
        "candidate_id": scored.candidate.candidate_id,
        "track": scored.candidate.track.value,
        "recommended_pathway": scored.recommended_pathway.value,
        "schema_version": DEFAULT_SCHEMA_VERSION,
        "markdown_path": str(markdown_path),
        "json_path": str(json_path),
        "config_version": _config_version(scored),
        "code_commit": git_commit(),
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "provenance_summary": candidate_provenance_record(scored.candidate).as_dict(),
        "plot_artifacts": [artifact.as_manifest_entry() for artifact in plot_artifacts],
    }


def report_manifest_json(
    scored: ScoredCandidate,
    *,
    markdown_path: Path,
    json_path: Path,
    plot_artifacts: tuple[PlotArtifact, ...] = (),
    indent: int = 2,
) -> str:
    """Serialize a report persistence manifest."""

    return json.dumps(
        report_manifest(
            scored,
            markdown_path=markdown_path,
            json_path=json_path,
            plot_artifacts=plot_artifacts,
        ),
        indent=indent,
        sort_keys=True,
    )


def candidate_markdown_report(
    scored: ScoredCandidate,
    *,
    plot_artifacts: tuple[PlotArtifact, ...] = (),
) -> str:
    """Render a conservative Markdown candidate review packet."""

    packet = candidate_packet(scored)
    scores = packet["scores"]
    return "\n".join(
        [
            f"# Candidate Review Packet: {packet['candidate_id']}",
            "",
            "## Conservative Claim Statement",
            "",
            REQUIRED_DISCLAIMER,
            "",
            "## Summary",
            "",
            f"- Candidate ID: `{packet['candidate_id']}`",
            f"- Track: `{packet['track']}`",
            f"- Recommended pathway: `{packet['recommended_pathway']}`",
            "- False-positive probability: "
            f"{_format_probability(scores['false_positive_probability'])}",
            "- Signal reality confidence: "
            f"{_format_probability(scores['signal_reality_confidence'])}",
            f"- Follow-up value: {_format_probability(scores['followup_value'])}",
            f"- Review readiness: {_format_probability(scores['review_readiness'])}",
            "",
            "## Operator Review",
            "",
            *_format_mapping(packet["operator_review"]),
            "",
            "## Posterior",
            "",
            *_format_mapping(packet["posterior"]),
            "",
            "## Positive Evidence",
            "",
            *_format_list(packet["positive_evidence"]),
            "",
            "## Negative Evidence",
            "",
            *_format_list(packet["negative_evidence"]),
            "",
            "## Blocking Issues",
            "",
            *_format_list(packet["blocking_issues"]),
            "",
            "## False-Positive Discussion",
            "",
            packet["false_positive_discussion"],
            "",
            "## Provenance",
            "",
            *_format_mapping(packet["provenance"]),
            "",
            "## Diagnostics",
            "",
            *_format_mapping(_diagnostic_fields(packet["features"])),
            "",
            "## Plot Artifact Note",
            "",
            PLOT_ARTIFACT_DISCLAIMER,
            "",
            *_format_plot_artifacts(plot_artifacts),
            "",
            "## Source IDs",
            "",
            *_format_list(packet["source_ids"]),
            "",
            "## Features",
            "",
            *_format_mapping(packet["features"]),
            "",
        ]
    )


def _operator_review(scored: ScoredCandidate) -> dict[str, Any]:
    pathway = scored.recommended_pathway
    follow_up_required = pathway in {
        Pathway.HUMAN_REVIEW_QUEUE,
        Pathway.CANDIDATE_REVIEW_PACKET,
        Pathway.EXTERNAL_FOLLOWUP_CANDIDATE,
    }
    action_by_pathway = {
        Pathway.KNOWN_OBJECT_ANNOTATION: "record_known_explanation",
        Pathway.DO_NOT_SUBMIT_FALSE_POSITIVE: "record_non_detection_or_false_positive",
        Pathway.GITHUB_REPRODUCIBILITY_ONLY: "preserve_reproducibility_artifact",
        Pathway.HUMAN_REVIEW_QUEUE: "local_human_review_required",
        Pathway.CANDIDATE_REVIEW_PACKET: "prepare_local_candidate_review_packet",
        Pathway.EXTERNAL_FOLLOWUP_CANDIDATE: "local_follow_up_review_required",
    }
    return {
        "follow_up_required": follow_up_required,
        "operator_action": action_by_pathway.get(pathway, "review_pathway_before_action"),
        "pathway": pathway.value,
        "pathway_basis": "Derived from the scoring model's recommended_pathway.",
        "detection_claimed": False,
        "external_submission_allowed": False,
    }


def _false_positive_discussion(scored: ScoredCandidate) -> str:
    negative_count = len(scored.evidence.negative_evidence)
    blocking_count = len(scored.evidence.blocking_issues)
    probability = scored.scores.false_positive_probability

    if negative_count == 0 and blocking_count == 0:
        return (
            "No strong false-positive evidence is present in the synthetic v0 feature "
            "packet, but false positives remain the default hypothesis until external "
            "review and independent validation."
        )

    return (
        f"The v0 scorer estimates a false-positive probability of "
        f"{_format_probability(probability)}. The packet records {negative_count} "
        f"negative evidence item(s) and {blocking_count} blocking issue(s). These "
        "must be resolved or explicitly accepted before any external follow-up."
    )


def _format_probability(value: object) -> str:
    if isinstance(value, int | float):
        return f"{float(value):.3f}"
    return str(value)


def _format_mapping(mapping: dict[str, Any]) -> list[str]:
    if not mapping:
        return ["- None recorded"]
    return [f"- `{key}`: {value}" for key, value in sorted(mapping.items())]


def _format_list(items: list[str]) -> list[str]:
    if not items:
        return ["- None recorded"]
    return [f"- {item}" for item in items]


def _format_plot_artifacts(plot_artifacts: tuple[PlotArtifact, ...]) -> list[str]:
    if not plot_artifacts:
        return ["- None generated"]
    return [
        f"- [{artifact.description}]({artifact.path}) "
        f"`{artifact.kind}` `{artifact.media_type}`"
        for artifact in plot_artifacts
    ]


def _diagnostic_fields(features: dict[str, Any]) -> dict[str, Any]:
    diagnostic_keys = {
        key
        for key in features
        if key.endswith("_path") or key.startswith("diagnostic_") or "plot" in key
    }
    return {key: features[key] for key in sorted(diagnostic_keys)}


def _safe_filename(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip(".-_")
    if not normalized:
        return "candidate-report"
    return normalized[:120]


def _config_version(scored: ScoredCandidate) -> str:
    return str(scored.candidate.provenance.get("config_version", DEFAULT_SCORING_CONFIG_VERSION))
